name: Snyk Open Source Scans

concurrency:
  group: snyk-opensource-actions-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    branches: [checks_requested]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4
        run: npm install --location=global node-jq
        run: npm i -g snyk-delta
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test --json --print-deps | snyk-delta

          
     # - run: npm install -g snyk
      - run: snyk auth ${{ secrets.SNYK_GH_ACTIONS_TOKEN }}
      - run: snyk test --all-projects --org=${{ vars.SNYK_ORG }}
